import "@shawnsandy/first-paint/dist/css/libs/all.min.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { PG } from "@fpkit/nextjs";
import Nav from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <PG.Footer orgName="Org Name">
          <p>
            Thank you for visiting our website! If you have any questions or
            comments, please don&apos;t hesitate to contact us.
          </p>
        </PG.Footer>
      </body>
    </html>
  );
}
